//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/InputSystem/PlayerMovementNew.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerMovementNew: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerMovementNew()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerMovementNew"",
    ""maps"": [
        {
            ""name"": ""PlayerActionsInput"",
            ""id"": ""06984c4a-35bc-4c90-87d0-2a467a274041"",
            ""actions"": [
                {
                    ""name"": ""DebugMessage"",
                    ""type"": ""Button"",
                    ""id"": ""de4cbebf-9ef3-4cd4-8a45-d417f62d627a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovingHorisontal"",
                    ""type"": ""PassThrough"",
                    ""id"": ""abb2a030-89c6-4785-8a54-ff59d38b7b3d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""bab2045f-a5d9-44ac-a0aa-a4d4575102d0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToLobby"",
                    ""type"": ""Button"",
                    ""id"": ""764b9a33-6005-44dc-bebc-5dde34baa0d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeleteProgress"",
                    ""type"": ""Button"",
                    ""id"": ""8f50ea2a-c45c-494b-89dc-445d6da0d696"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SitInRobot"",
                    ""type"": ""Button"",
                    ""id"": ""48b21e34-57ca-4a34-860d-e56515a880fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5a559dd7-06fe-4fa8-b190-bb02bf1b113a"",
                    ""path"": ""<Keyboard>/f8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugMessage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19ffbc8e-bb71-4ad2-b6cd-f384df7af230"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80ee1834-8d74-45ed-8e43-9a979c8c96e9"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""MovingHorisontal"",
                    ""id"": ""ade2ed2c-9480-47e2-bcf5-a4ffc3b1a769"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""74c6b793-578f-4ed4-a11d-4ae292c85453"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a3431e6b-e92b-42b5-8b4a-180d2a82122a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5b53c93d-41d9-457e-a82b-f6a767022150"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9b2f3b55-7ace-44bb-a61c-abacbb7865a7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""21b02f9c-4517-47a3-a384-4846c77c9bfb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f5008667-0332-4642-9060-8594af0da9c1"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9dea9714-109b-4e1f-b645-03825ba5dbcc"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7c77ca38-044f-4c3f-b35a-225e84b3b282"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8c39e813-b650-4d13-bc98-ef545291d25e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e077cb13-f23f-493b-b8af-110507868004"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToLobby"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31e81e2c-647a-47be-bb5f-da1490ac5582"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeleteProgress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ee85df6-5e86-47c3-8e42-8e44c7fe854c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SitInRobot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""AT_ATControl"",
            ""id"": ""f5443e53-4b4d-4cba-9730-c6dc24ec7437"",
            ""actions"": [
                {
                    ""name"": ""MovingHorisontal"",
                    ""type"": ""PassThrough"",
                    ""id"": ""efd090c0-bda5-4f02-9546-ed24369402e3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""8d94cc5c-c102-4b14-936b-758d90199ab0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldObject"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ae552890-746d-48cf-bca1-3f318423e6dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lever"",
                    ""type"": ""Button"",
                    ""id"": ""8d859409-8d0d-4543-acad-cb7383cb3ef3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RobotExit"",
                    ""type"": ""Button"",
                    ""id"": ""6bc68780-5dd7-4ad6-859f-6260b76d5a85"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8956b646-b79a-4fde-9b1b-58b927326366"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e12efbfb-e832-4bb7-932f-b74560271fc7"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lever"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2db57921-c421-42b0-a8e5-8fbcff562ee5"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lever"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""MovingHorisontal"",
                    ""id"": ""4a1cfef0-d8d5-4aa7-bf08-7f9bdfc973bf"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cedf2d7f-0ba8-4fb9-a5eb-6eb66e6b75eb"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""36fe1ea7-6304-40d6-b2d9-53bd4a8da031"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""eee5d20e-643a-4026-956f-cb72905afe32"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6fee641c-64fe-4cec-b5fb-6a2f96bf6bf7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""39156216-4828-4d5c-bf8f-533294973685"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a4b7993b-4a63-4ef1-a8f2-28e859d286dd"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0c9ed4ad-d70d-4b7b-9038-5f38aeeb92dc"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""88727027-4d75-41fe-9f33-e2135b6a62b5"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""73f8bc74-1640-4861-b198-6b569b9eb045"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovingHorisontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a130b2a7-6751-4a97-b278-dfac40022077"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fdd4bdaa-e344-4f72-82e4-125d47de7de1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74a3e53c-cac2-462a-8106-b5ce97bc24ef"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RobotExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerActionsInput
        m_PlayerActionsInput = asset.FindActionMap("PlayerActionsInput", throwIfNotFound: true);
        m_PlayerActionsInput_DebugMessage = m_PlayerActionsInput.FindAction("DebugMessage", throwIfNotFound: true);
        m_PlayerActionsInput_MovingHorisontal = m_PlayerActionsInput.FindAction("MovingHorisontal", throwIfNotFound: true);
        m_PlayerActionsInput_Jump = m_PlayerActionsInput.FindAction("Jump", throwIfNotFound: true);
        m_PlayerActionsInput_ToLobby = m_PlayerActionsInput.FindAction("ToLobby", throwIfNotFound: true);
        m_PlayerActionsInput_DeleteProgress = m_PlayerActionsInput.FindAction("DeleteProgress", throwIfNotFound: true);
        m_PlayerActionsInput_SitInRobot = m_PlayerActionsInput.FindAction("SitInRobot", throwIfNotFound: true);
        // AT_ATControl
        m_AT_ATControl = asset.FindActionMap("AT_ATControl", throwIfNotFound: true);
        m_AT_ATControl_MovingHorisontal = m_AT_ATControl.FindAction("MovingHorisontal", throwIfNotFound: true);
        m_AT_ATControl_Jump = m_AT_ATControl.FindAction("Jump", throwIfNotFound: true);
        m_AT_ATControl_HoldObject = m_AT_ATControl.FindAction("HoldObject", throwIfNotFound: true);
        m_AT_ATControl_Lever = m_AT_ATControl.FindAction("Lever", throwIfNotFound: true);
        m_AT_ATControl_RobotExit = m_AT_ATControl.FindAction("RobotExit", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerActionsInput
    private readonly InputActionMap m_PlayerActionsInput;
    private List<IPlayerActionsInputActions> m_PlayerActionsInputActionsCallbackInterfaces = new List<IPlayerActionsInputActions>();
    private readonly InputAction m_PlayerActionsInput_DebugMessage;
    private readonly InputAction m_PlayerActionsInput_MovingHorisontal;
    private readonly InputAction m_PlayerActionsInput_Jump;
    private readonly InputAction m_PlayerActionsInput_ToLobby;
    private readonly InputAction m_PlayerActionsInput_DeleteProgress;
    private readonly InputAction m_PlayerActionsInput_SitInRobot;
    public struct PlayerActionsInputActions
    {
        private @PlayerMovementNew m_Wrapper;
        public PlayerActionsInputActions(@PlayerMovementNew wrapper) { m_Wrapper = wrapper; }
        public InputAction @DebugMessage => m_Wrapper.m_PlayerActionsInput_DebugMessage;
        public InputAction @MovingHorisontal => m_Wrapper.m_PlayerActionsInput_MovingHorisontal;
        public InputAction @Jump => m_Wrapper.m_PlayerActionsInput_Jump;
        public InputAction @ToLobby => m_Wrapper.m_PlayerActionsInput_ToLobby;
        public InputAction @DeleteProgress => m_Wrapper.m_PlayerActionsInput_DeleteProgress;
        public InputAction @SitInRobot => m_Wrapper.m_PlayerActionsInput_SitInRobot;
        public InputActionMap Get() { return m_Wrapper.m_PlayerActionsInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionsInputActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActionsInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsInputActionsCallbackInterfaces.Add(instance);
            @DebugMessage.started += instance.OnDebugMessage;
            @DebugMessage.performed += instance.OnDebugMessage;
            @DebugMessage.canceled += instance.OnDebugMessage;
            @MovingHorisontal.started += instance.OnMovingHorisontal;
            @MovingHorisontal.performed += instance.OnMovingHorisontal;
            @MovingHorisontal.canceled += instance.OnMovingHorisontal;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @ToLobby.started += instance.OnToLobby;
            @ToLobby.performed += instance.OnToLobby;
            @ToLobby.canceled += instance.OnToLobby;
            @DeleteProgress.started += instance.OnDeleteProgress;
            @DeleteProgress.performed += instance.OnDeleteProgress;
            @DeleteProgress.canceled += instance.OnDeleteProgress;
            @SitInRobot.started += instance.OnSitInRobot;
            @SitInRobot.performed += instance.OnSitInRobot;
            @SitInRobot.canceled += instance.OnSitInRobot;
        }

        private void UnregisterCallbacks(IPlayerActionsInputActions instance)
        {
            @DebugMessage.started -= instance.OnDebugMessage;
            @DebugMessage.performed -= instance.OnDebugMessage;
            @DebugMessage.canceled -= instance.OnDebugMessage;
            @MovingHorisontal.started -= instance.OnMovingHorisontal;
            @MovingHorisontal.performed -= instance.OnMovingHorisontal;
            @MovingHorisontal.canceled -= instance.OnMovingHorisontal;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @ToLobby.started -= instance.OnToLobby;
            @ToLobby.performed -= instance.OnToLobby;
            @ToLobby.canceled -= instance.OnToLobby;
            @DeleteProgress.started -= instance.OnDeleteProgress;
            @DeleteProgress.performed -= instance.OnDeleteProgress;
            @DeleteProgress.canceled -= instance.OnDeleteProgress;
            @SitInRobot.started -= instance.OnSitInRobot;
            @SitInRobot.performed -= instance.OnSitInRobot;
            @SitInRobot.canceled -= instance.OnSitInRobot;
        }

        public void RemoveCallbacks(IPlayerActionsInputActions instance)
        {
            if (m_Wrapper.m_PlayerActionsInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActionsInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActionsInputActions @PlayerActionsInput => new PlayerActionsInputActions(this);

    // AT_ATControl
    private readonly InputActionMap m_AT_ATControl;
    private List<IAT_ATControlActions> m_AT_ATControlActionsCallbackInterfaces = new List<IAT_ATControlActions>();
    private readonly InputAction m_AT_ATControl_MovingHorisontal;
    private readonly InputAction m_AT_ATControl_Jump;
    private readonly InputAction m_AT_ATControl_HoldObject;
    private readonly InputAction m_AT_ATControl_Lever;
    private readonly InputAction m_AT_ATControl_RobotExit;
    public struct AT_ATControlActions
    {
        private @PlayerMovementNew m_Wrapper;
        public AT_ATControlActions(@PlayerMovementNew wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovingHorisontal => m_Wrapper.m_AT_ATControl_MovingHorisontal;
        public InputAction @Jump => m_Wrapper.m_AT_ATControl_Jump;
        public InputAction @HoldObject => m_Wrapper.m_AT_ATControl_HoldObject;
        public InputAction @Lever => m_Wrapper.m_AT_ATControl_Lever;
        public InputAction @RobotExit => m_Wrapper.m_AT_ATControl_RobotExit;
        public InputActionMap Get() { return m_Wrapper.m_AT_ATControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AT_ATControlActions set) { return set.Get(); }
        public void AddCallbacks(IAT_ATControlActions instance)
        {
            if (instance == null || m_Wrapper.m_AT_ATControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AT_ATControlActionsCallbackInterfaces.Add(instance);
            @MovingHorisontal.started += instance.OnMovingHorisontal;
            @MovingHorisontal.performed += instance.OnMovingHorisontal;
            @MovingHorisontal.canceled += instance.OnMovingHorisontal;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @HoldObject.started += instance.OnHoldObject;
            @HoldObject.performed += instance.OnHoldObject;
            @HoldObject.canceled += instance.OnHoldObject;
            @Lever.started += instance.OnLever;
            @Lever.performed += instance.OnLever;
            @Lever.canceled += instance.OnLever;
            @RobotExit.started += instance.OnRobotExit;
            @RobotExit.performed += instance.OnRobotExit;
            @RobotExit.canceled += instance.OnRobotExit;
        }

        private void UnregisterCallbacks(IAT_ATControlActions instance)
        {
            @MovingHorisontal.started -= instance.OnMovingHorisontal;
            @MovingHorisontal.performed -= instance.OnMovingHorisontal;
            @MovingHorisontal.canceled -= instance.OnMovingHorisontal;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @HoldObject.started -= instance.OnHoldObject;
            @HoldObject.performed -= instance.OnHoldObject;
            @HoldObject.canceled -= instance.OnHoldObject;
            @Lever.started -= instance.OnLever;
            @Lever.performed -= instance.OnLever;
            @Lever.canceled -= instance.OnLever;
            @RobotExit.started -= instance.OnRobotExit;
            @RobotExit.performed -= instance.OnRobotExit;
            @RobotExit.canceled -= instance.OnRobotExit;
        }

        public void RemoveCallbacks(IAT_ATControlActions instance)
        {
            if (m_Wrapper.m_AT_ATControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAT_ATControlActions instance)
        {
            foreach (var item in m_Wrapper.m_AT_ATControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AT_ATControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AT_ATControlActions @AT_ATControl => new AT_ATControlActions(this);
    public interface IPlayerActionsInputActions
    {
        void OnDebugMessage(InputAction.CallbackContext context);
        void OnMovingHorisontal(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnToLobby(InputAction.CallbackContext context);
        void OnDeleteProgress(InputAction.CallbackContext context);
        void OnSitInRobot(InputAction.CallbackContext context);
    }
    public interface IAT_ATControlActions
    {
        void OnMovingHorisontal(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnHoldObject(InputAction.CallbackContext context);
        void OnLever(InputAction.CallbackContext context);
        void OnRobotExit(InputAction.CallbackContext context);
    }
}
